### ISSUE TITLE
Payment Acceptance Error Page

### ISSUE THREAD

**Issue by MaddyLIN** [Arcadier/Developer-Community-Support#2]
**Describe the bug**
I have changed the mandatory payment from Paypal in the admin account. Now our user/host is logging in as: Merchant account jillfidouser1@gmail.com

Under Settings, she goes to her payment acceptance and tries to link to stripe as her form of preferred payment acceptance but we get an error page.

Once she gets this error page nothing else works, the site seems to freeze and we have trouble logging out.

**To Reproduce**
1. Set Stripe as payment method from the Admin portal
2. Onboard as a merchant and try to link another Stripe account.
3. See this error page:

![Error Page Stripe](https://user-images.githubusercontent.com/49678975/56202128-f2f31300-6074-11e9-95f8-fc021df2593e.png)

**Comment by Arcadier** [comment]
Hi Maddy!
Thanks for contacting us here, may we suggest for issues with the basic product, please contact the support through your admin portal :) as we would want to facillitate these pages for developer customisation discussion!

It seems you had not connected your stripe payment settings correctly. Do check out our article on how to connect here: 
https://support.arcadier.com/hc/en-us/articles/115001376913-Setting-up-your-payment-gateway-Stripe-
If you are still facing issues, as stated, please contact arcadier support!
